In [30]:
import numpy as np
from numpy.linalg import eig

a = np.array([[2,1,2],
              [1,3,2],
              [2,4,1]])

characteristicEquation =  np.poly(a)
print("Characteristic equation : ", characteristicEquation[:3])

print("\n")
c1 = round(characteristicEquation[0])
c2 = round(characteristicEquation[1])
c3 = round(characteristicEquation[2])
print("Coefficient of λ^2 :", c1)
print("Coefficient of λ :",  c2)
print("Constant term :", c3)
print("\nCharacteristic equation in λ : ")
print("(", c1, ")λ^2 + (", c2, ")λ + (" , c3, ")")
print("\n")

value, vector = eig(a)

print("Eigenvalue : ", value)
print("Eigenvector : ", vector)
print("\n")

print("Explanation : ")
for i in range(len(value)):
    print("When eigenvalue = ", value[i], ", the eigenvector is ", vector[:,i])

print("\n")
print("Check proving Ax = λx : ")
x = vector[:, 0]
lambdaOriginal = value[0]

Ax = np.dot(a,x)
lambdaX = lambdaOriginal * x

if np.allclose(Ax, lambdaX):
    print("Proved\nAx = λx")
    print("Ax = ", Ax)
    print("λx = ", lambdaX)
else :
    print("Ax ≠ λx")

Characteristic equation :  [ 1. -6. -2.]


Coefficient of λ^2 : 1
Coefficient of λ : -6
Constant term : -2

Characteristic equation in λ : 
( 1 )λ^2 + ( -6 )λ + ( -2 )


Eigenvalue :  [ 6.02911192  1.33625596 -1.36536788]
Eigenvector :  [[-0.47185751 -0.88987496 -0.42138925]
 [-0.58896955  0.45081499 -0.29617582]
 [-0.65609859  0.0699171   0.85715284]]


Explanation : 
When eigenvalue =  6.029111920025985 , the eigenvector is  [-0.47185751 -0.58896955 -0.65609859]
When eigenvalue =  1.3362559632125934 , the eigenvector is  [-0.88987496  0.45081499  0.0699171 ]
When eigenvalue =  -1.3653678832385765 , the eigenvector is  [-0.42138925 -0.29617582  0.85715284]


Check proving Ax = λx : 
Proved
Ax = λx
Ax =  [-2.84488175 -3.55096334 -3.95569181]
λx =  [-2.84488175 -3.55096334 -3.95569181]


In [1]:
#Build-in function

import numpy as np
from numpy.linalg import eig

a = np.array([[1,2,1],
              [1,3,2],
              [1,4,2]])

w, v = eig(a)

print("Eigen Value : ", w)
print("Eigen Vector : ", v)

#Verify Av = Bv

b_1 = w[0]
v_1 = v[:, 0]

Av = np.dot(a, v_1)
Bv = b_1 * v_1

print(np.allclose(Av, Bv))

Eigen Value :  [ 5.97196077  0.42346527 -0.39542603]
Eigen Vector :  [[-0.38285759 -0.93567397  0.18171141]
 [-0.60097347  0.10061581 -0.53826044]
 [-0.70160599  0.33821692  0.82295605]]
True


In [12]:
#The Power Method

import numpy as np

def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n

x = np.array([1, 0, 0]) #Initial Vector
a = np.array([[2,1,2],
              [1,3,2],
              [2,4,1]])

for i in range(10):
    x = np.dot(a, x)
    lambda_1, x = normalize(x)

print("Eigen Value : ", lambda_1)
print("Eigen Vector : ", x)

Eigen Value :  6.029103563824766
Eigen Vector :  [0.71918796 0.8976846  1.        ]


In [14]:
#The Inverse Power Method
import numpy as np
from numpy.linalg import inv

x = np.array([1, 0,0])
a = np.array([[2,1,2],
              [1,3,2],
              [2,4,1]])
a_inv = inv(a)

for i in range(10):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print("Eigen Value : ", lambda_1)
print("Eigen Vector : ", x)

Eigen Value :  0.9934991520973002
Eigen Vector :  [ 1.         -0.35899914 -0.31722874]


In [9]:
#The QR Method

import numpy as np
from numpy.linalg import qr

a = np.array([[2,1,2],
              [1,3,2],
              [2,4,1]])

q, r = qr(a)

print("Q : ", q)
print("R : ", r)

b = np.dot(q, r)
print("QR : ", b)

Q :  [[-0.66666667  0.7028635  -0.24806947]
 [-0.33333333 -0.57882876 -0.74420841]
 [-0.66666667 -0.41344912  0.62017367]]
R :  [[-3.         -4.33333333 -2.66666667]
 [ 0.         -2.68741925 -0.16537965]
 [ 0.          0.         -1.36438208]]
QR :  [[2. 1. 2.]
 [1. 3. 2.]
 [2. 4. 1.]]


In [10]:
#The QR Method with iteration

import numpy as np
from numpy.linalg import qr

a = np.array([[2,1,2],
              [1,3,2],
              [2,4,1]])

p = [1, 5, 10, 20]

for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i + 1 in p:
        print(f"Iteration {i + 1} : ")
        print(a)

Iteration 1 : 
[[ 5.22222222  1.50219845  2.31531505]
 [ 1.00605951  1.62393162  1.8974359 ]
 [ 0.90958805  0.56410256 -0.84615385]]
Iteration 5 : 
[[ 6.02812002e+00  3.75618790e-01  1.72575407e+00]
 [ 3.17029489e-03  1.24119039e+00  1.15958282e+00]
 [ 2.82220427e-03  2.14708273e-01 -1.26931041e+00]]
Iteration 10 : 
[[ 6.02911198e+00  6.73669653e-01 -1.62959103e+00]
 [ 2.66148816e-06  1.40199227e+00 -6.73686284e-01]
 [ 1.78779828e-06  2.70029791e-01 -1.43110425e+00]]
Iteration 20 : 
[[ 6.02911192e+00  7.12863476e-01 -1.61283217e+00]
 [ 7.72198323e-13  1.41009131e+00 -6.04983479e-01]
 [ 6.37828516e-13  3.38731545e-01 -1.43920323e+00]]


In [ ]:
#Grafik Eigenvectors

import numpy as np
import matplotlib.pyplot as plt

def plot_vect(x, b, xlim, ylim):
    plt.figure(figsize=(10, 6))
    plt.quiver(0, 0, x[0], x[1], color='k', angles='xy', scale_units='xy', scale=1, label='Original vector')
    plt.quiver(0, 0, b[0], b[1], color='g', angles='xy', scale_units='xy', scale=1, label='Transformed vector')
    plt.xlim(xlim)
    plt.ylim(ylim)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.legend()
    plt.show()

a = np.array([[2, 1, 2],
              [1, 3, 2],
              [2, 4, 1]])
x = np.array([[1], [0], [0]])  
plot_vect(x, b, (0, 3), (0, 2))
