In [5]:
#Gauss Manual

import numpy as np

def gaussElimination(A, B):
    n = len(A)
    for i in range(n):
        maxRow = i
        for k in range(i+1, n):
            if abs(A[k][i]) > abs(A[maxRow][i]):
                maxRow = k
        A[i], A[maxRow] = A[maxRow], A[i]
        B[i], B[maxRow] = B[maxRow], B[i]
        for k in range(i+1, n):
            faktor = A[k][i] / A[i][i]
            B[k] -= faktor * B[i]
            for j in range(i, n):
                A[k][j] -= faktor * A[i][j]
    X = [0] * n
    for i in range(n-1, -1, -1):
        X[i] = B[i] / A[i][i]
        for k in range(i-1, -1, -1):
            B[k] -= A[k][i] * X[i]
    return X

A = [[3,1,-2],[-2,-9,-7],[1,1,7]]

X = np.array([2, 5, -3])

solution = gaussElimination(A, X)

print("Equations :\n")
print("4𝑥1 + 𝑥2 - 2𝑥3 = 2")
print("-2𝑥1 - 8𝑥2 -  7𝑥3 = 5")
print("𝑥1 + 𝑥2 + 8𝑥3 = -3")

print("\nEquations to Matrix\n")
print("[4\t-1\t-2]\t[x1]\t    [2]")
print("[-2\t-8\t-7]\t[x2]\t=   [14]")
print("[1\t 1\t 8]\t[x3]\t    [54]")

print("\nAugmented Matrix : \n")
a = [[4, 1, -2, 2],
     [-2, -8, -7, 5],
     [1, 1, 8,-3]]
print(a)

print("\nResult:")
for i, x in enumerate(solution):
    rounded_x = round(x, 3)
    print(f"x{i+1} = {rounded_x}")


Equations :

4𝑥1 + 𝑥2 - 2𝑥3 = 2
-2𝑥1 - 8𝑥2 -  7𝑥3 = 5
𝑥1 + 𝑥2 + 8𝑥3 = -3

Equations to Matrix

[4	-1	-2]	[x1]	    [2]
[-2	-8	-7]	[x2]	=   [14]
[1	 1	 8]	[x3]	    [54]

Augmented Matrix : 

[[4, 1, -2, 2], [-2, -8, -7, 5], [1, 1, 8, -3]]

Result:
x1 = 0.333
x2 = -0.36
x3 = -0.286


In [4]:
#Gauss Jordan Manual

import numpy as np

def gaussJordanElimination(A, B):
    n = len(A)
    M = A
    i = 0
    for x in M:
        x.append(B[i])
        i += 1
    for k in range(n):
        for i in range(k, n):
            if abs(M[i][k]) > abs(M[k][k]):
                M[k], M[i] = M[i], M[k]
            else:
                pass
        for j in range(k+1, n):
            q = M[j][k] / M[k][k]
            for m in range(k, n+1):
                M[j][m] -= q * M[k][m]
    x = [0 for i in range(n)]
    x[n-1] = M[n-1][n] / M[n-1][n-1]
    for i in range(n-1, -1, -1):
        z = 0
        for j in range(i+1, n):
            z = z  + M[i][j]*x[j]
        x[i] = (M[i][n] - z) / M[i][i]
    return x

A = [[3,1,-2],[-2,-9,-7],[1,1,7]]

X = np.array([2, 5, -3])

solution = gaussJordanElimination(A, X)

print("Equations :\n")
print("4𝑥1 + 𝑥2 - 2𝑥3 = 2")
print("-2𝑥1 - 8𝑥2 -  7𝑥3 = 5")
print("𝑥1 + 𝑥2 + 8𝑥3 = -3")

print("\nEquations to Matrix\n")
print("[4\t-1\t-2]\t[x1]\t    [2]")
print("[-2\t-8\t-7]\t[x2]\t=   [14]")
print("[1\t 1\t 8]\t[x3]\t    [54]")

print("\nAugmented Matrix : \n")
a = [[4, 1, -2, 2],
     [-2, -8, -7, 5],
     [1, 1, 8,-3]]
print(a)

print("\nResult:")
print(gaussJordanElimination(A,X),"\n")
for i, x in enumerate(solution):
    rounded_x = round(x, 3)
    print(f"x{i+1} = {rounded_x}")

Equations :

4𝑥1 + 𝑥2 - 2𝑥3 = 2
-2𝑥1 - 8𝑥2 -  7𝑥3 = 5
𝑥1 + 𝑥2 + 8𝑥3 = -3

Equations to Matrix

[4	-1	-2]	[x1]	    [2]
[-2	-8	-7]	[x2]	=   [14]
[1	 1	 8]	[x3]	    [54]

Augmented Matrix : 

[[4, 1, -2, 2], [-2, -8, -7, 5], [1, 1, 8, -3]]

Result:
[0.46857142857142847, -0.30857142857142844, -0.45142857142857146] 

x1 = 0.469
x2 = -0.309
x3 = -0.451


In [3]:
#Numpy

import numpy as np

a = [[3,1,-2],[-2,-9,-7],[1,1,7]]

X = np.array([2, 5, -3])

result = np.linalg.solve(A,X)

np.set_printoptions(precision=3)

print(result)

[ 0.469 -0.309 -0.451]


In [2]:
#Scipy

import numpy as np
from scipy.linalg import solve

# Coefficients matrix
A = [[3,1,-2],[-2,-9,-7],[1,1,7]]

# Constants
b = np.array([2, 5, -3])

# Solve the system of linear equations
solution = solve(A, b)

print("Solution:")
print(solution)


Solution:
[ 0.46857143 -0.30857143 -0.45142857]


In [1]:
#Gauss Seidel

import numpy as np

a = [[3,1,-2],[-2,-9,-7],[1,1,7]]


#Diagonal dominant atau tidak
diag = np.diag(np.abs(a))
off_diag = np.sum(np.abs(a), axis=1) - diag
if np.all(diag > off_diag):
    print("Matrix is diagonally dominat")
else :
    print("NOT diagonally doominant")

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1,x2,x3])

print("Iteration results")
print("k,       x1,     x2,     x3")
for k in range(1,50):
    x1 = (2-1*x2+2*x3)/3
    x2 = (5+2*x1+7*x3)/(-9)
    x3 = (-3-1*x1-1*x2)/7
    x = np.array([x1,x2,x3])
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k,x1,x2,x3))
    if dx < epsilon:
        converged = True
        print("Converged")
        break
    
    x_old = x
    
if not converged:
    print ("Not converge, increase the # of iterations")

NOT diagonally doominant
Iteration results
k,       x1,     x2,     x3
1, 0.6667, -0.7037, -0.4233
2, 0.6190, -0.3639, -0.4650
3, 0.4780, -0.3001, -0.4540
4, 0.4640, -0.3056, -0.4512
5, 0.4677, -0.3086, -0.4513
Converged


In [8]:
#Lower & Upper

import numpy as np
from scipy.linalg import lu

A = np.array([[4, 1, -2],
              [-2, -8, -7],
              [1, 1, 8]]) #Hitung absnya buat lbh safety

P, L, U = lu(A)
print("P :\n", P)
print("L :\n", L)
print("U :\n", U)
print("LU :\n", np.dot(L,U))

P :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L :
 [[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.25 -0.1   1.  ]]
U :
 [[ 4.   1.  -2. ]
 [ 0.  -7.5 -8. ]
 [ 0.   0.   7.7]]
LU :
 [[ 4.  1. -2.]
 [-2. -8. -7.]
 [ 1.  1.  8.]]


In [11]:
#Vector

import numpy as np

vector_row = np.array([[1,-5,3,2,4]])
vector_col = np.array([[1],
                       [2],
                       [3],
                       [4],
                       ])
print(vector_row.shape)
print(vector_col.shape)

(1, 5)
(4, 1)


In [12]:
#Vector Norm

import numpy as np
from numpy.linalg import norm

vector_row = np.array([[1,-5,3,2,4]])
vector_col = np.array([[1],
                       [2],
                       [3],
                       [4],
                       ])

new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector,1)
norm_2 = norm(new_vector,2)
norm_inf = norm(new_vector, np.inf)
print("L_1 is : %.1f"%norm_1)
print("L_2 is : %.1f"%norm_2)
print("L_inf is : %.1f"%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is : 15.0
L_2 is : 7.4
L_inf is : 5.0


In [13]:
#Dot Product

from numpy import arccos, dot

v = np.array([10,9,3])
w = np.array([2,5,12])
theta = arccos(dot(v,w.T)/(norm(v)*norm(w)))
print(theta)

0.979924710443726


In [14]:
#Cross Product

import numpy as np

v = np.array([[0,2,0]])
w = np.array([[3,0,0]])
print(np.cross(v,w))

[[ 0  0 -6]]


In [16]:
#Determinan & Inverse

import numpy as np
from numpy.linalg import det
from numpy.linalg import inv

M = np.array([[0,2,1,3],
              [3,2,8,1],
              [1,0,0,3],
              [0,3,2,1]])
print("M :\n", M)
print("Determinant : %.1f"%det(M))
I = np.eye(4)
print("I :\n", I)
print("M*I :\n", np.dot(M,I))

print("Inv :\n", inv(M))

M :
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant : -38.0
I :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I :
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]
Inv :
 [[-1.579 -0.079  1.237  1.105]
 [-0.632 -0.132  0.395  0.842]
 [ 0.684  0.184 -0.553 -0.579]
 [ 0.526  0.026 -0.079 -0.368]]


In [ ]:
#Condition number & Rank & Augmented Matrix

import numpy as np
from scipy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])
print("Condition number :\n", cond(A))
print("Rank : ", matrix_rank(A))
y = np.array([[1], [2],[3]])
A_y = np.concatenate((A,y),axis = 1)
print("Augmented matrix :\n", A_y)